with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: mockery
packages:
  github.com/ar4ie13/shortener/internal/service:
    interfaces:
      Repository:
        config:
          dir: "{{.InterfaceDir}}/internal/mockery"