package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const (
	generateComment = "// generate:reset"
	outputFileName  = "reset.gen.go"
	resetTemplate   = `// Code generated by cmd/reset. DO NOT EDIT.
package {{.PackageName}}

{{range .Structs}}
func (x *{{.Name}}) Reset() {
	if x == nil {
		return
	}
	{{range .Fields}}{{.Code}}
	{{end}}
}
{{end}}
`
)

type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

type FieldInfo struct {
	Code string
}

type ResetGen struct {
	PackageName string
	Structs     []StructInfo
}

func main() {
	if len(os.Args) > 1 {
		// Specific directory can be passed
		err := processDir(os.Args[1])
		if err != nil {
			log.Fatal(err)
		}
		return
	}

	// By default - current directory
	err := processDir(".")
	if err != nil {
		log.Fatal(err)
	}
}

func processDir(root string) error {
	return filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}

		pkgFiles, err := parser.ParseDir(token.NewFileSet(), path, nil, parser.ParseComments)
		if err != nil {
			return nil
		}

		for pkgName, pkg := range pkgFiles {
			if err = processPackage(path, pkgName, pkg); err != nil {
				log.Printf("Error processing package %s in %s: %v", pkgName, path, err)
			}
		}
		return nil
	})
}

func processPackage(dir, pkgName string, pkg *ast.Package) error {
	var structures []structTypeInfo

	for _, file := range pkg.Files {
		ast.Inspect(file, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.GenDecl:
				if x.Tok != token.TYPE {
					return true
				}
				for _, spec := range x.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					if hasGenerateResetComment(x.Doc) {
						if st, ok := typeSpec.Type.(*ast.StructType); ok {
							structures = append(structures, structTypeInfo{
								Name:   typeSpec.Name.Name,
								Fields: st.Fields.List,
							})
						}
					}
				}
			}
			return true
		})
	}

	if len(structures) == 0 {
		return nil
	}

	return generateResetFile(dir, pkgName, structures)
}

func hasGenerateResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.HasPrefix(strings.TrimSpace(c.Text), generateComment) {
			return true
		}
	}
	return false
}

type structTypeInfo struct {
	Name   string
	Fields []*ast.Field
}

func generateResetFile(dir, pkgName string, structs []structTypeInfo) error {
	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	gen := &ResetGen{
		PackageName: pkgName,
		Structs:     make([]StructInfo, 0, len(structs)),
	}

	for _, st := range structs {
		fieldInfos := make([]FieldInfo, 0, len(st.Fields))
		for _, field := range st.Fields {
			for _, name := range field.Names {
				fieldName := name.Name
				expr := field.Type

				resetCode := generateFieldResetCode("x", fieldName, expr, 1)
				if resetCode != "" {
					fieldInfos = append(fieldInfos, FieldInfo{Code: resetCode})
				}
			}
		}

		gen.Structs = append(gen.Structs, StructInfo{
			Name:   st.Name,
			Fields: fieldInfos,
		})
	}

	var buf bytes.Buffer
	if err = tmpl.Execute(&buf, gen); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated code: %w", err)
	}

	outputPath := filepath.Join(dir, outputFileName)
	return os.WriteFile(outputPath, formatted, 0644)
}

func generateFieldResetCode(receiver, fieldName string, expr ast.Expr, indent int) string {
	indentStr := strings.Repeat("\t", indent)

	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128",
			"byte", "rune":
			return fmt.Sprintf("%s%s.%s = 0", indentStr, receiver, fieldName)

		case "string":
			return fmt.Sprintf("%s%s.%s = \"\"", indentStr, receiver, fieldName)

		case "bool":
			return fmt.Sprintf("%s%s.%s = false", indentStr, receiver, fieldName)

		default:
			return tryResetMethod(indentStr, receiver, fieldName)
		}

	case *ast.ArrayType:

		if t.Len == nil {
			return fmt.Sprintf("%s%s.%s = %s.%s[:0]", indentStr, receiver, fieldName, receiver, fieldName)
		}

		return fmt.Sprintf("%sfor i := range %s.%s {\n"+
			"%s\t%s.%s[i] = %s\n"+
			"%s}",
			indentStr,
			receiver, fieldName,
			indentStr,
			receiver, fieldName,
			zeroValueForType(t.Elt),
			indentStr)

	case *ast.MapType:
		return fmt.Sprintf("%sclear(%s.%s)", indentStr, receiver, fieldName)

	case *ast.StarExpr:
		// *T
		inner := generateFieldResetCode(receiver+"."+fieldName, "", t.X, indent+1)
		if inner == "" {
			return ""
		}
		return fmt.Sprintf("%sif %s.%s != nil {\n"+
			"%s\n"+
			"%s}",
			indentStr,
			receiver, fieldName,
			inner,
			indentStr)

	case *ast.StructType:
		return tryResetMethod(indentStr, receiver, fieldName)

	default:
		return tryResetMethod(indentStr, receiver, fieldName)
	}
}

func tryResetMethod(indent, receiver, fieldName string) string {
	if fieldName == "" {
		// Direct struct
		return fmt.Sprintf("%sif r, ok := interface{ Reset() }(%s).(interface{ Reset() }); ok {\n"+
			"%s\tr.Reset()\n"+
			"%s}",
			indent, receiver,
			indent+"\t",
			indent,
		)
	}

	return fmt.Sprintf("%sif r, ok := interface{ Reset() }(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {\n"+
		"%s\tr.Reset()\n"+
		"%s}",
		indent, receiver, fieldName,
		receiver, fieldName,
		indent+"\t",
		indent,
	)
}

func zeroValueForType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128", "byte", "rune":
			return "0"
		case "string":
			return "\"\""
		case "bool":
			return "false"
		default:
			return "nil"
		}
	default:
		return "nil"
	}
}
