package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const (
	generateComment = "// generate:reset"
	outputFileName  = "reset.gen.go"
	resetTemplate   = `// Code generated by cmd/reset. DO NOT EDIT.
package {{.PackageName}}

{{range .Structs}}
func (x *{{.Name}}) Reset() {
	if x == nil {
		return
	}
	{{range .Fields}}{{.Code}}
	{{end}}
}
{{end}}
`
)

type (
	StructInfo struct {
		Name   string
		Fields []FieldInfo
	}
	FieldInfo struct {
		Code string
	}
	ResetGen struct {
		PackageName string
		Structs     []StructInfo
	}
	structTypeInfo struct {
		Name   string
		Fields []*ast.Field
	}
)

func main() {
	if len(os.Args) > 1 {
		// Can pass a specific directory as an argument
		err := processDir(os.Args[1])
		if err != nil {
			log.Fatal(err)
		}
		return
	}

	// By default - current directory
	err := processDir(".")
	if err != nil {
		log.Fatal(err)
	}
}

func processDir(root string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Dir:  root,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return fmt.Errorf("failed to load packages: %w", err)
	}

	for _, pkg := range pkgs {
		if err := processPackage(root, pkg); err != nil {
			log.Printf("Error processing package %s: %v", pkg.PkgPath, err)
		}
	}
	return nil
}

func processPackage(root string, pkg *packages.Package) error {
	var structures []structTypeInfo

	for _, file := range pkg.Syntax {
		ast.Inspect(file, func(n ast.Node) bool {
			decl, ok := n.(*ast.GenDecl)
			if !ok || decl.Tok != token.TYPE {
				return true
			}

			for _, spec := range decl.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if !hasGenerateResetComment(decl.Doc) {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				structures = append(structures, structTypeInfo{
					Name:   ts.Name.Name,
					Fields: st.Fields.List,
				})
			}
			return true
		})
	}

	if len(structures) == 0 {
		return nil
	}

	dir := root
	if len(pkg.GoFiles) > 0 {
		dir = filepath.Dir(pkg.GoFiles[0])
	}

	return generateResetFile(dir, pkg.Name, structures)
}

func hasGenerateResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.HasPrefix(strings.TrimSpace(c.Text), generateComment) {
			return true
		}
	}
	return false
}

func generateResetFile(dir, pkgName string, structs []structTypeInfo) error {
	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	gen := &ResetGen{
		PackageName: pkgName,
		Structs:     make([]StructInfo, 0, len(structs)),
	}

	for _, st := range structs {
		var fields []FieldInfo
		for _, field := range st.Fields {
			for _, name := range field.Names {
				code := generateFieldResetCode("x", name.Name, field.Type, 1)
				if code == "" {
					continue
				}
				fields = append(fields, FieldInfo{Code: code})
			}
		}

		if len(fields) == 0 {
			continue
		}

		gen.Structs = append(gen.Structs, StructInfo{
			Name:   st.Name,
			Fields: fields,
		})
	}

	if len(gen.Structs) == 0 {
		return nil
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, gen); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated code: %w", err)
	}

	outputPath := filepath.Join(dir, outputFileName)
	return os.WriteFile(outputPath, formatted, 0644)
}

// generateFieldResetCode рекурсивно генерирует код сброса для поля
func generateFieldResetCode(receiver, fieldName string, expr ast.Expr, indent int) string {
	indentStr := strings.Repeat("\t", indent)

	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128",
			"byte", "rune":
			return fmt.Sprintf("%s%s.%s = 0", indentStr, receiver, fieldName)

		case "string":
			return fmt.Sprintf("%s%s.%s = \"\"", indentStr, receiver, fieldName)

		case "bool":
			return fmt.Sprintf("%s%s.%s = false", indentStr, receiver, fieldName)

		default:
			return tryResetMethod(indentStr, receiver, fieldName)
		}

	case *ast.ArrayType:
		// []T — slice
		if t.Len == nil {
			return fmt.Sprintf("%s%s.%s = %s.%s[:0]", indentStr, receiver, fieldName, receiver, fieldName)
		}

		// [N]T — array
		return fmt.Sprintf("%s%s.%s = %s.%s{}", indentStr, receiver, fieldName, receiver, fieldName)

	case *ast.MapType:
		return fmt.Sprintf("%sclear(%s.%s)", indentStr, receiver, fieldName)

	case *ast.StarExpr:
		// *T
		inner := generateFieldResetCode(receiver+"."+fieldName, "", t.X, indent+1)
		if inner == "" {
			return ""
		}
		return fmt.Sprintf("%sif %s.%s != nil {\n"+
			"%s\n"+
			"%s}",
			indentStr,
			receiver, fieldName,
			inner,
			indentStr)

	case *ast.StructType:
		return tryResetMethod(indentStr, receiver, fieldName)

	default:
		return tryResetMethod(indentStr, receiver, fieldName)
	}
}

func tryResetMethod(indent, receiver, fieldName string) string {
	innerIndent := indent + "\t"

	if fieldName == "" {
		return fmt.Sprintf(`
%sif r, ok := any(%s).(interface{ Reset() }); ok {
%s	r.Reset()
%s}`,
			indent, receiver,
			innerIndent, indent,
		)
	}

	multiline := `
%sif r, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {
%s	r.Reset()
%s}`
	return fmt.Sprintf(multiline, indent, receiver, fieldName, receiver, fieldName, innerIndent, indent)
}
